name: Release

on: workflow_dispatch

jobs:
  release:
    runs-on: macos-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Require whole history to compute the incremental build number

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - uses: actions/cache@v3
        with:
          key: kotlin-native-${{ hashFiles('gradle.properties') }}
          path: ~/.konan

      - uses: gradle/gradle-build-action@v2
        env:
          MAVEN_AWS_KEY: ${{ secrets.MIREGO_MAVEN_AWS_ACCESS_KEY_ID }}
          MAVEN_AWS_SECRET: ${{ secrets.MIREGO_MAVEN_AWS_SECRET_ACCESS_KEY }}
        with:
          arguments: check release -i -s
